### ISSUE TITLE
Can we purdy plz get a release?

### ISSUE THREAD

**Issue by hhff** [bustlelabs/ember-cli-image#2]

**Comment by hhff** [comment]
Bumping this!  I'm still getting `Install failed. Could not find addon with name: ember-cli-image`

I'm wanting to use this in an OS project!

**Comment by gdub22** [comment]
Hey, thanks for your interest.  You should be able to point directly to the github repo if you'd like to use it.  I would not recommend it in its currently state.  We have a simpler and 2.0 compatible rewrite that we'll publish soon.

**Comment by hhff** [comment]
Thanks garth!
