### ISSUE TITLE
"Could not find addon." How are things going over here? 

### ISSUE THREAD

**Issue by sheriffderek** [bustlelabs/ember-cli-image#3]
Excited to try out this add-on but CLI says it can't be found. What your status over there? : )

```
$: ember install ember-cli-image
Installed packages for tooling via npm.
Install failed. Could not find addon with name: ember-cli-image
```

**Comment by gdub22** [comment]
`npm install ember-cli-image` should work to install it.  This project is unmaintained at this point - use at your own risk.
