### ISSUE TITLE
The npm release is empty :(

### ISSUE THREAD

**Issue by oscarni** [bustlelabs/ember-cli-image#4]
Tried to use this addon, but the npm release only contained readme and package.json. All other files are missing. Using this repo as for now, but would be cool if you released it 👍

**Comment by rileytaylor** [comment]
@gdub22 @MaazAli Bumping this issue. No problem with npm installing from git, but an npm release would be fantastic!

**Comment by gpoitch** [comment]
Was not able to update this on npm because it was published under a non-existing user.
I do not recommend using this code, as it is very outdated and will not be maintained.
